server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/games-service
    username: postgres
    password: ""
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update